version: 1.0.0.{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
  - choco install gitversion.portable -pre -y

skip_commits:
  files:
    - '**/*.md'
    
before_build:
  - dotnet --info
  - ps: gitversion /l console /output buildserver 

build_script:
 - ps: .\build.ps1 -Target "AppVeyor"
 
test: off

artifacts:
  - path: '**/unleash.featuretoggle.client.*.nupkg' # find all NuGet packages recursively