version: 1.0.0.{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
  - dotnet --info

build_script:
 - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1
 
test: off

artifacts:
  - path: '**/Unleash.*.nupkg' # find all NuGet packages recursively